name: "[CI] Test"

on:
  push:
  pull_request:

jobs:
  test-report:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Install Ruby deps
        run: |
          gem install bundler:2.1.4
          bundle install  --jobs 4 --retry 3

      - name: Install Appraisal
        run: |
          bundle exec appraisal install

      - name: Setup Database
        run: bundle exec appraisal rake test_app
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec appraisal rake
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r "$CC_TEST_REPORTER_ID"
        env:
          CC_TEST_REPORTER_ID: 094100f11a0b69b24e4deab7adc5532006239e0803a8b1964b3000766bca5de1